// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDork(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddDork'](arg1, arg2, arg3, arg4);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteDork(arg1) {
  return window['go']['main']['App']['DeleteDork'](arg1);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetDorks() {
  return window['go']['main']['App']['GetDorks']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function RunGoogleDork(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunGoogleDork'](arg1, arg2, arg3);
}
