// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDork(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.DorkEntry>;

export function ClearHistory():Promise<boolean>;

export function DeleteDork(arg1:string):Promise<boolean>;

export function GetCategories():Promise<Array<string>>;

export function GetDorks():Promise<Array<main.DorkEntry>>;

export function GetHistory():Promise<Array<main.HistoryEntry>>;

export function GetStats():Promise<Record<string, number>>;

export function RunGoogleDork(arg1:string,arg2:string,arg3:string):Promise<main.SearchResult>;
